fix(time-signature): support lower >= 10
tonaljs/tonal pull request #351
Opened 2022-11-28 12:11 UTC by manniL

Resolves #348

2022-11-28 17:22 UTC, manniL commented
According to #348, the implementation is a bit more difficult 😄

2022-11-28 17:22 UTC, danigb requested changes
Thanks for the PR! A couple of things:

- It would be nice to add some documentation at the README
- As you can probably [read](https://github.com/tonaljs/tonal/issues/348#issuecomment-1329462394) I was reluctant to add this kind of signatures... The problem that I see is that now any fractional can be parsed as a time signature, and I'm not sure (I don't know about irrational time signatures enough) that all them are valid time signatures... So I'd like to find (if any) an example of a valid fraction that is not a valid time signature, and add it to the tests... For example, is `123/231934` a valid irrational time signature? I don't know... (but my music theory intuition says no)

2022-11-28 17:22 UTC, danigb commented on packages/time-signature/test.ts
> +      type: "irregular",
As I mentioned in the issue, this is an `irrational` time signature.

2022-11-28 17:22 UTC, danigb commented on packages/time-signature/test.ts
> +  test("get lower >= 10", () => {
I guess we could change the test name...

```suggestion
  test("irrational time signatures", () => {
```

2022-11-28 21:30 UTC, manniL commented
Valid points! Sadly, my music theory knowledge is *very* limited and I don't know much about irrational time signatures either 🙈

The question is - are there even "invalid" time signatures except having a 0 as upper/lower?

2022-11-29 22:27 UTC, danigb approved these changes
Great! 🚀  Thanks! 🙌

2022-11-29 22:27 UTC, merged